name: Build Container and Push to AWS ECR

on:
  workflow_call:
    inputs:
      container-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      tags:
        required: true
        type: string
      platforms:
        required: true
        type: string
    secrets:
      aws-oidc-role:
        required: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    name: Build for multi-platform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PLATFORM: ${{ inputs.platforms }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-oidc-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.container-name }}
          tags: ${{ inputs.tags }}
          flavor: suffix=-${{ matrix.platform }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.PLATFORM }}
      - uses: cloudposse/github-action-matrix-outputs-write@main
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.PLATFORM }}
          outputs: |-
            digest: ${{ steps.build.outputs.digest }}

  merge-manifest:
    needs:
      - build
    name: Merge image of multi-platform
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-oidc-role }}
          aws-region: ${{ inputs.aws-region }}
      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.container-name }}
          tags: ${{ inputs.tags }}
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: build
      - name: map to array
        id: array
        run: |
          result="$(echo '${{ steps.read.outputs.result }}' | jq -c '.digest | to_entries | map(.value) | join(",")')"
          echo "result=${result}" >> $GITHUB_OUTPUT
      - uses: fdkevin0/docker-manifest-create-action@v1
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          digests: ${{ fromJson(steps.array.outputs.result) }}