name: Build Container and Push to AWS ECR

on:
  push:
    branches: [main]
    tags: [v*]
    paths:
      - Dockerfile
      - .github/workflows/aws-build-container-e2e.yml
      - .github/workflows/aws-build-container.yml
  pull_request:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/aws-build-container-e2e.yml
      - .github/workflows/aws-build-container.yml

jobs:
  call-build-container:
    uses:./.github/workflows/aws-build-container.yml
    with:
      container-name: alpine
      aws-oidc-role: ${{ secrets.AWS_OIDC_ROLE }}
      aws-region: us-east-2
      tags: |
        type=schedule
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=sha
      platforms:
        - linux/amd64
        - linux/arm64
